import { StyleSheet } from "react-native";
export const tStyles = StyleSheet.create({
  ticketPage: {
    backgroundColor: "#193247",
    height: "100%",
  },
  ticket: {
    position: "absolute",
    top: 410,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
    transform: [{ rotate: "90deg" }],
    borderWidth: 10,
    borderColor: "#ffff",
    zIndex: -1,
    elevation: 1,
    shadowColor: "#ffff",
    shadowOffset: { width: 12, height: -10 },
    shadowOpacity: 0.8,
    shadowRadius: 3,
  },
  sMissionName: {
    position: "relative",
    transform: [{ rotate: "90deg" }],
    top: 330,
    left: 50,
    right: 0,
    bottom: 0,
    zIndex: 1,
  },
  sRocketName: {
    position: "relative",
    transform: [{ rotate: "90deg" }],
    top: 320,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1,
  },
  sRocketType: {
    position: "relative",
    transform: [{ rotate: "90deg" }],
    top: 450,
    left: -5,
    right: 0,
    bottom: 0,
    zIndex: 1,
  },
  sLaunchYear: {
    position: "relative",
    transform: [{ rotate: "90deg" }],
    top: 650,
    left: 80,
    right: 0,
    bottom: 0,
    zIndex: 1,
  },
  backButton: {
    marginLeft: 15,
  },
});
